### ISSUE TITLE
Discuss when the BFD session is created

### ISSUE THREAD

**Issue by jhaas-pfrc** [aceelindem/ietf-bgp-strict-mode#10]
Ketan raises the point that we discuss state machine interactions, but we don't go into enough detail to say when BFD needs to be started vs. BGP.  We do discuss the other direction a bit in terms of the BFD holddown procedures.

**Comment by aceelindem** [comment]
Since an established BFD session is required for BGP, it would seem that BFD must be started for session establishment. If it is not started, this is either a misconfiguration or a bug.

**Comment by jhaas-pfrc** [comment]
The consideration is which kicks off which.  BFD may not have a session established or even configured until BGP comes up in some implementations.  However, given protocol delays, you may want to start BFD upon configuration without starting the BGP FSM yet.

Juniper ran into a form of this issue related to timeouts when the BFD sessions were started as part of protocol state actions.  The goal for addressing this issue will be normative text that describes when the feature needs things to start, and potentially some helpful informative text about reasons to start things early or not.

**Comment by jhaas-pfrc** [comment]
Added a section covering this detail.
