### ISSUE TITLE
How to represent bfd strict configuration in FSM text

### ISSUE THREAD

**Issue by jhaas-pfrc** [aceelindem/ietf-bgp-strict-mode#11]
As part of Ketan's review, he's asking whether the BfdEnabled session attribute should, instead of being boolean, be a choice of enabled/disabled/bfd-strict-enabled.

There's a desire to include "bfd strict enable".  Review in the upcoming FSM work whether we squish this into the current BfdEnabled or whether there's motivation to have a separable BfdStrictEnabled.

My impression prior to full analysis is we need carefully only refer to the negotiated results in the FSM for the BGP capability, and the BFD session state.  The current text does have bfdenabled and bfd session state evaluated together.  Re-evaluate.

**Comment by jhaas-pfrc** [comment]
A little further audit is showing that current use of BfdEnabled as being needed for distinguishing that it is configured and the BFD session state may not be up.  So, overloading the strict configuration adds branch case text for each time this value is referred to in the FSM.  However, if the updated text results in always pairing the strict check as well, it still motivates the merge.

Note that there's no YANG module extension in this draft and this issue overlaps what configuration of BFD and configuration of strict look like.  The BFD YANG module provides a generic grouping that is leveraged in the IETF BGP module.  The strict mode behavior would be an augmentation in the BGP YANG module as part of using that grouping.

**Comment by jhaas-pfrc** [comment]
Mercia's comments:

> [MZ] Given that most vendors have implemented the Strict-mode as a configurable
> option knob for BFD which can be enabled or disabled, we may want to clarify
> BfdEnabled and StrictBfdEnabled, or just simply use StrictBfdEnabled.
>      
> - BfdEnabled: A boolean or bit flag when the base BFD is configured and enabled for this BGP session.
> - StrictBfdEnabled: A boolean or bit flag when the strict-mode BFD is configured and enabled for this BGP session.
>      or
> We could simply use StrictBfdEnabled instead of BfdEnabled since the Strict-mode can only be enabled
> with BFD.

**Comment by jhaas-pfrc** [comment]
KT> Can the event be BfdConfigChange and the config result updated in the
BfdEnabled attribute?

[MZ] If either Bfd or Bfd Strict-mode is deconfigured/disabled for a BGP peer session, 
     it'll be equivalent to BfdStrict_Disabled, and the session attributes 
     (StrictBfdEnabled) will be updated per received BfdStrict_Disabled event.
     Jeff, if we want to handle both the base and strict BFD modes, then we need to
     define the separated session attributs( e.g. BfdEnabled and StrictBfdEnabled).

**Comment by jhaas-pfrc** [comment]
Chose to keep the config elements separate.  This will impact YANG module along with vendor details.

**Comment by merciaz** [comment]
Thanks Jeff for closing #11.
